# Generated by Django 2.1.7 on 2019-05-27 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Finished', 'Finished'), ('Unfinished', 'Unfinished')], default='Unfinished', max_length=10)),
                ('completion_date', models.DateField(verbose_name='date for completion')),
                ('warning_if_delayed', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='warning of delaying')),
                ('description', models.TextField(max_length=500)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('completion_date',),
            },
        ),
    ]
