# Generated by Django 2.1.7 on 2019-03-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='slug',
        ),
        migrations.AddField(
            model_name='task',
            name='delayed',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
