# Generated by Django 2.1.7 on 2019-05-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190325_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='warning_of_delaying',
        ),
        migrations.AddField(
            model_name='task',
            name='warning_if_delayed',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='warning of delaying'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completion_date',
            field=models.DateField(verbose_name='date for completion'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Finished', 'Finished'), ('Unfinished', 'Unfinished')], default='Unfinished', max_length=10),
        ),
    ]
